// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/wslynn/wechat-gozero/app/group/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/group/add_friend",
				Handler: AddFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/group/handle_friend",
				Handler: HandleFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/group/group_user_list",
				Handler: GroupUesrListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/group/message_group_info_list",
				Handler: MessageGroupInfoListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
