// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/wslynn/wechat-gozero/app/msg/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/message/upload",
				Handler: uploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/message/pull",
				Handler: pullHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
