// Code generated by goctl. DO NOT EDIT!
// Source: group.proto

package groupclient

import (
	"context"

	"ws_chat/app/group/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendRequest             = proto.AddFriendRequest
	AddFriendResponse            = proto.AddFriendResponse
	ChatMsg                      = proto.ChatMsg
	GroupUserListRequest         = proto.GroupUserListRequest
	GroupUserListResponse        = proto.GroupUserListResponse
	HandleFriendRequest          = proto.HandleFriendRequest
	HandleFriendResponse         = proto.HandleFriendResponse
	MessageGroupInfo             = proto.MessageGroupInfo
	MessageGroupInfoListRequest  = proto.MessageGroupInfoListRequest
	MessageGroupInfoListResponse = proto.MessageGroupInfoListResponse

	GroupClient interface {
		AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
		HandleFriend(ctx context.Context, in *HandleFriendRequest, opts ...grpc.CallOption) (*HandleFriendResponse, error)
		GroupUserList(ctx context.Context, in *GroupUserListRequest, opts ...grpc.CallOption) (*GroupUserListResponse, error)
		MessageGroupInfoList(ctx context.Context, in *MessageGroupInfoListRequest, opts ...grpc.CallOption) (*MessageGroupInfoListResponse, error)
	}

	defaultGroupClient struct {
		cli zrpc.Client
	}
)

func NewGroupClient(cli zrpc.Client) GroupClient {
	return &defaultGroupClient{
		cli: cli,
	}
}

func (m *defaultGroupClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	client := proto.NewGroupClientClient(m.cli.Conn())
	return client.AddFriend(ctx, in, opts...)
}

func (m *defaultGroupClient) HandleFriend(ctx context.Context, in *HandleFriendRequest, opts ...grpc.CallOption) (*HandleFriendResponse, error) {
	client := proto.NewGroupClientClient(m.cli.Conn())
	return client.HandleFriend(ctx, in, opts...)
}

func (m *defaultGroupClient) GroupUserList(ctx context.Context, in *GroupUserListRequest, opts ...grpc.CallOption) (*GroupUserListResponse, error) {
	client := proto.NewGroupClientClient(m.cli.Conn())
	return client.GroupUserList(ctx, in, opts...)
}

func (m *defaultGroupClient) MessageGroupInfoList(ctx context.Context, in *MessageGroupInfoListRequest, opts ...grpc.CallOption) (*MessageGroupInfoListResponse, error) {
	client := proto.NewGroupClientClient(m.cli.Conn())
	return client.MessageGroupInfoList(ctx, in, opts...)
}
