// Code generated by goctl. DO NOT EDIT.
package types

type UploadRequest struct {
	GroupId string `json:"groupId"`
	Type    int64  `json:"type"`
	Content string `json:"content"`
	Uuid    string `json:"uuid"`
}

type UploadResponse struct {
	Id         int64 `json:"id"`
	CreateTime int64 `json:"createTime"`
}

type PullRequest struct {
	Platform string `json:"platform"`
	GroupId  string `json:"groupId"`
	MaxMsgId int64  `json:"maxMsgId"`
}

type ChatMsg struct {
	Id         int64  `json:"id"`
	GroupId    string `json:"groupId"`
	SenderId   int64  `json:"senderId"`
	Type       int64  `json:"type"`
	Content    string `json:"content"`
	Uuid       string `json:"uuid"`
	CreateTime int64  `json:"createTime"`
}

type PullResponse struct {
	List []*ChatMsg `json:"list"`
}
