// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6,max=16"`
	NickName string `json:"nickName,optional" validate:"-"`                 // 可选
	Gender   int64  `json:"gender,optional,default=0" validate:"oneof=0 1"` // 默认为0
}

type RegisterResponse struct {
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6,max=16"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type PersonalInfoRequest struct {
}

type PersonalInfoResponse struct {
	UserId    int64  `json:"userId"`
	NickName  string `json:"nickName"`
	Gender    int64  `json:"gender"`
	Email     string `json:"email"`
	AvatarUrl string `json:"avatarUrl"`
}
